const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");

const chatbotSchema = new mongoose.Schema(
  {
    user_id: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "Sign_up", // Reference the correct collection
      required: true 
    },
    bot_name: { type: String, required: true },
    expected_age: { type: Number, required: true, min: 1, max: 100 },
    gender: { 
      type: String, 
      enum: ["Male", "Female", "Other"], 
      required: true 
    },
    nationality: { type: String, required: true },
    hobbies: { type: [String], default: [] },
    occupation: { type: String, required: true },
    personal_traits: { type: [String], default: [] },
    goals: { type: [String], default: [] },
    preferred_communication_style: { type: String, required: true },
    interests: { type: [String], default: [] },
    passion: { type: String, required: true },
    past_story: { type: String, required: true },
    childhood_favorites: { type: [String], default: [] },
    all_favorites: { type: [String], default: [] },
    strengths: { type: [String], default: [] },
    weaknesses: { type: [String], default: [] },
    stress_factors: { type: [String], default: [] },
    traumas: { type: [String], default: [] },
    motivation: { type: String, required: true },
    inspiration: { type: String, required: true },

    // Ensuring only one purpose is selected
    bot_purpose: { 
      type: String, 
      required: true,
      enum: ["Personal Assistant", "Accountant", "Engineer", "Doctor", "Teacher",
    "Customer Support", "Legal Advisor", "Therapist", "Fitness Coach",
    "Tech Support", "Business Consultant", "AI Researcher", "Medical Assistant",
    "Student", "Software Developer", "Marketing Specialist", "Data Analyst",
    "Project Manager", "Psychologist", "Language Tutor", "Financial Advisor",
    "Entrepreneur", "HR Manager", "Gamer", "Mathematician", "Cybersecurity Expert",
    "Digital Artist", "Musician", "Content Creator", "Legal Consultant",
    "Mechanical Engineer", "Civil Engineer", "Electrical Engineer",
    "Blockchain Developer", "Crypto Trader", "Stock Market Analyst",
    "Startup Consultant", "Public Speaker", "Scientist", "Astronomer",
    "Biologist", "Chemist", "Physicist", "Social Media Influencer",
    "Sports Coach", "Nutritionist", "Event Planner", "Political Analyst",
    "Philosopher", "E-commerce Specialist", "UX Designer", "UI Designer",
    "Climate Change Analyst", "Sustainability Consultant", "Ethical Hacker",
    "Penetration Tester", "Game Designer", "Voice Actor", "Translator",
    "Legal Researcher", "AI Ethics Specialist", "Prompt Engineer",
    "Metaverse Consultant", "Virtual Reality Guide", "AR Developer",
    "Technical Writer", "Medical Coder", "Veterinary Assistant", "Dentist Assistant",
    "Clinical Psychologist", "Child Therapist", "Life Coach", "Spiritual Advisor",
    "Reiki Healer", "Energy Coach", "AI Storyteller", "Content Scheduler",
    "Podcast Host", "Video Editor", "Film Critic", "Movie", "Fashion Consultant",
    "Interior Designer", "Architect Assistant", "Landscape Designer",
    "Drone Operator", "Aviation Specialist", "Travel Planner", "Tour Guide",
    "Visa Assistant", "Immigration Consultant", "Language Interpreter",
    "Patent Specialist", "Legal Contract Reviewer", "Compliance Officer",
    "Risk Analyst", "Insurance Agent", "Loan Officer", "Credit Analyst",
    "Forex Trader", "Microeconomist", "Macroeconomist", "Business Intelligence Analyst",
    "Quantitative Analyst", "Machine Learning Trainer", "Computer Vision Expert",
    "NLP Expert", "Robotics Instructor", "Bioinformatics Analyst",
    "Genetic Counselor", "Zoologist", "Botanist", "Oceanographer", "Geologist",
    "Hydrologist", "Astrophysicist", "Quantum Physicist", "Material Scientist",
    "Product Manager", "Agile Coach", "Scrum Master", "DevOps Engineer",
    "Site Reliability Engineer", "Full Stack Developer", "Mobile Developer",
    "iOS Developer", "Android Developer", "React Developer", "Vue.js Expert",
    "Next.js Expert", "SEO Specialist", "Copywriter", "Ad Campaign Manager",
    "Brand Strategist", "PR Specialist", "Affiliate Marketer", "Email Marketing",
    "Sales Enablement", "Cold Outreach", "Lead Generation", "Survey Conductor",
    "Job Interview Coach", "Resume Builder", "Career Counselor", "LinkedIn Coach",
    "Mental Health", "Daily Motivation", "Mindfulness Coach", "Dream Interpreter",
    "Sleep Tracker", "Voice UX Specialist", "Neuropsychologist", "Behavioral Economist",
    "AI Debate Coach", "Space Mission Planner", "Deep Sea Explorer", "Eco-Tourism Planner",
    "Wildlife Conservationist", "Botany Research Assistant", "Mycologist",
    "Agricultural Advisor", "Farm Automation Consultant", "Aquaponics Expert",
    "Hydroponics Coach", "AgriTech Specialist", "Disaster Response Coordinator",
    "Emergency Alert Assistant", "Public Safety Advisor", "First Aid Guide",
    "CPR Trainer", "Drone Surveillance Operator", "Home Automation Planner",
    "Smart Home Consultant", "Home Security Advisor", "Remote Elder Care Assistant",
    "Parenting Coach", "Child Development Advisor", "Teen Counseling",
    "School Admissions Advisor", "College Application Mentor", "Study Planner",
    "Online Exam Proctor", "AI Math Tutor", "Science Lab Assistant",
    "Homework Checker", "Programming Interview Coach", "Competitive Programming",
    "Bug Tracking Assistant", "API Documentation Helper", "Open Source Contributor",
    "Remote Job Assistant", "Freelance Gig", "Job Matching Assistant",
    "Workplace Wellness Coach", "Employee Feedback Collector", "Team Building Coach",
    "Conflict Resolution", "Meeting Minutes Assistant", "Productivity Tracker",
    "Time Blocking Assistant", "Startup Idea Validator", "Business Name Generator",
    "Pitch Deck Reviewer", "Investor Outreach Assistant", "Crowdfunding Coach",
    "Ethical Business Consultant", "SaaS Product Advisor", "Subscription Management",
    "Digital Invoice Generator", "Accounting", "HR Policy", "Diversity Coach",
    "Employee Onboarding Assistant", "Exit Interview Collector", "Company Culture Promoter",
    "Online Dating Coach", "Breakup Support", "Wedding Planner", "Anniversary Reminder",
    "Gift Recommendation", "Pet Care Advisor", "Dog Training", "Pet Adoption Assistant",
    "Aquarium Maintenance", "Vet Appointment Scheduler", "Food Tracker", "Recipe Assistant",
    "Grocery List Builder", "Meal Prep Planner", "Calorie Counter", "Restaurant Reviewer",
    "Food Safety Advisor", "Barista Trainer", "Sommelier Assistant", "Home Chef Guide",
    "Eco-Living Advisor", "Recycling Guide", "Zero Waste Assistant",
    "Water Conservation Coach", "Carbon Footprint Tracker", "Ethical Shopping Guide",
    "Minimalist Lifestyle", "Digital Declutter Coach", "Screen Time Monitor",
    "Digital Wellbeing", "Self-Discipline Coach", "Productivity Challenge",
    "Personal KPI Tracker", "Daily Planner", "Goal Tracking Assistant"]
    },

    // Ensuring only one domain is selected
    bot_domain: {
      type: String,
      required: true,
      enum: [
        "Technology", "Healthcare", "Finance", "Education", "Law & Legal",
        "Business & Management", "Science & Research", "Entertainment & Media",
        "Art & Design", "Sports & Fitness", "Food & Culinary", 
        "Emerging Technologies", "Miscellaneous & Other"
      ]
    },
    bot_subdomain: {
      type: String,
      enum: [
        // 🔹 Technology (20)
        "Software Engineering", "Web Development", "Mobile App Development", "AI & Machine Learning",
        "Cybersecurity", "Cloud Computing", "IoT & Embedded Systems", "Game Development",
        "Blockchain & Cryptocurrency", "Big Data & Analytics", "Tech Support & IT Services",
        "Robotics & Automation", "AR & VR Development", "Networking & Infrastructure",
        "Programming Languages", "Open Source Development", "Quantum Computing",
        "UX/UI Design", "DevOps & CI/CD", "Ethical Hacking",

        // 🔹 Healthcare (20)
        "General Medicine", "Surgery", "Mental Health", "Pharmaceuticals",
        "Medical Research", "Public Health", "Healthcare Administration",
        "Alternative Medicine", "Nutrition & Dietetics", "Fitness & Wellness",
        "Cardiology", "Neurology", "Oncology", "Pediatrics", "Endocrinology",
        "Dermatology", "Radiology", "Pathology", "Emergency Medicine",
        "Physical Therapy & Rehabilitation",

        // 🔹 Finance (20)
        "Banking & Investment", "Personal Finance", "Stock Market",
        "Cryptocurrency", "Real Estate Finance", "Insurance & Risk Management",
        "Corporate Finance", "Taxation", "Wealth Management", "Financial Planning",
        "Economics", "Accounting & Auditing", "Microfinance", "Fintech & Digital Payments",
        "Trading Strategies", "Financial Regulations", "Retirement Planning",
        "Budgeting", "Business Valuation", "Forensic Accounting",

        // 🔹 Education (15)
        "Higher Education", "School Education", "E-learning & Online Courses",
        "Special Education", "EdTech & Learning Platforms", "Student Counseling",
        "STEM Education", "Educational Psychology", "Teacher Training",
        "Language Learning", "Adult Education", "Scholarships & Grants",
        "Career Guidance", "Exam Preparation", "Research & Academia",

        // 🔹 Law & Legal (10)
        "Corporate Law", "Criminal Law", "Civil Law", "Intellectual Property Law",
        "Human Rights Law", "International Law", "Tax Law", "Real Estate Law",
        "Immigration Law", "Employment Law",


        "Operations Management",
            "Project Management",
            "Supply Chain Management",
            "Logistics & Distribution",
            "Product Management",
            "Business Intelligence",
            "Change Management",
            "Risk Management",
            "Quality Control & Assurance",
            "Business Process Reengineering",
            "Corporate Governance",
            "Organizational Development",
            "Customer Relationship Management (CRM)",
            "Performance Management",
            "Strategic Planning",
            "Business Development",
            "International Business",
            "Franchise Management",
            "Procurement & Sourcing",
            "Lean Management",
            "Six Sigma",
            "Agile Business Practices",
            "Management Consulting",
            "Business Analytics",
            "Brand Management",
            "Sales Management",
            "Retail Management",
            "Merchandising Strategy",
            "Channel Management",
            "Inventory Management",
            "E-commerce Operations",
            "Startup Incubation",
            "Entrepreneurship Strategy",
            "Innovation Management",
            "Market Research",
            "Stakeholder Engagement",
            "Vendor Management",
            "Business Negotiation",
            "Digital Business Models",
            "Business Ethics & Compliance",
            "Genetics & Genomics",
            "Astrophysics & Space Research",
            "Quantum Physics",
            "Nuclear Science",
            "Particle Physics",
            "Materials Science",
            "Nanotechnology",
            "Environmental Science",
            "Ecology & Biodiversity",
            "Marine Biology",
            "Botany Research",
            "Zoology Research",
            "Climate Change Studies",
            "Geology & Earth Sciences",
            "Meteorology & Atmospheric Research",
            "Hydrology",
            "Oceanography",
            "Astronomy & Cosmology",
            "Bioinformatics",
            "Computational Biology",
            "Neuroscience Research",
            "Psychological Research",
            "Pharmaceutical Research",
            "Biomedical Engineering",
            "Cognitive Science",
            "Social Science Research",
            "Sociological Studies",
            "Anthropology & Archaeology",
            "Political Science Research",
            "Behavioral Science",
            "Forensic Science",
            "Agricultural Research",
            "Food Science & Technology",
            "Chemical Research",
            "Theoretical Physics",
            "Experimental Physics",
            "Scientific Writing & Publishing",
            "Grant Writing & Funding Research",
            "Lab Management & Coordination",
            "Peer Review & Academic Evaluation","Music Production",
            "Podcasting",
            "Streaming & Digital Content",
            "Radio Broadcasting",
            "Voice Acting",
            "Scriptwriting",
            "Video Editing & Post Production",
            "Animation & VFX",
            "Video Game Development",
            "Esports & Gaming",
            "Live Events & Concerts",
            "Stand-up Comedy",
            "Social Media Content Creation",
            "YouTube Channel Management",
            "Influencer Marketing",
            "Talent Management",
            "Modeling & Fashion Shows",
            "Photography & Videography",
            "Event Hosting",
            "Cinematography",
            "Media Journalism",
            "Pop Culture Analysis",
            "Movie Reviewing",
            "TV Show Commentary",
            "Music Reviewing",
            "Celebrity News & Gossip",
            "Digital Art & Illustration",
            "Meme Creation & Trends",
            "Short Film Production",
            "Online Radio Hosting",
            "Audiobook Narration",
            "Media Buying & Planning",
            "Sound Engineering",
            "Lyric Writing",
            "DJing & Mix Production",
            "Reality Show Analysis",
            "Virtual Concerts & Experiences","UI/UX Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Product Design",
            "3D Modeling & Animation",
            "Illustration & Digital Art",
            "Textile Design",
            "Printmaking",
            "Photography",
            "Sculpture & Ceramics",
            "Art Direction",
            "Motion Graphics",
            "Packaging Design",
            "Web Design",
            "Game Design & Development",
            "Environmental Design",
            "Furniture Design",
            "Jewelry Design",
            "Exhibition Design",
            "Editorial Design",
            "Visual Communication",
            "Advertising Design",
            "Branding & Identity Design",
            "Advertising & Media Design",
            "Interactive Media Design",
            "Concept Art",
            "Video Game Art",
            "Virtual Reality Design",
            "Augmented Reality Design",
            "Animation Production",
            "Art Restoration",
            "Street Art",
            "Fine Arts",
            "Art Criticism & Theory",
            "Art Education",
            "Museum Curating",
            "Art Installations",
            "Landscape Architecture",
            "Stage Design",
            "Lighting Design",
            "Sound Design",
            "Illustrative Storytelling",

        // 🔹 Sports & Fitness (20)
        "Football (Soccer)", "Basketball", "Cricket", "Baseball", "Tennis", "Golf",
        "Athlete Training & Coaching", "Sports Psychology", "Esports & Competitive Gaming",
        "Strength Training", "Cardio & Endurance Training", "Bodybuilding",
        "Martial Arts & Self-Defense", "Yoga & Meditation", "Rehabilitation & Physical Therapy",
        "Adventure Sports (Skydiving, Rock Climbing, etc.)", "Olympic Sports",
        "Paralympic & Adaptive Sports", "Personal Fitness Coaching",
        "Extreme Sports",
        "Food Science",
        "Nutrition & Dietetics",
        "Baking & Pastry Arts",
        "Culinary Management",
        "Restaurant Management",
        "Culinary Tourism",
        "Food Photography",
        "Food Styling",
        "Catering & Event Planning",
        "Sustainability in Food",
        "Food Safety & Hygiene",
        "Gastronomy",
        "Ethnic & International Cuisines",
        "Molecular Gastronomy",
        "Food Innovation & Technology",
        "Culinary Education & Training",
        "Wine & Beverage Management",
        "Dietitian Services",
        "Food & Beverage Marketing",
        "Food Product Development",
        "Food Service Operations",
        "Food Packaging",
        "Meal Planning",
        "Food Writing & Blogging",
        "Food Entrepreneurship",
        "Food Waste Management",
        "Food Logistics & Supply Chain",
        "Restaurant Branding & Marketing",
        "Culinary Health Coaching",
        "Food Manufacturing & Processing",
        "Health & Wellness Cuisine",
        "Food Sustainability & Ethics",
        "Culinary Nutrition",
        "Food Innovation & Trends",
        "Vegan & Vegetarian Culinary Arts",
        "Farm-to-Table Movement",
        "Artisanal & Local Food",
        "Food Safety & Compliance",
        "Gourmet & Fine Dining",
        "Cooking Techniques & Methods",
        "Food Engineering & Innovation",
        "Machine Learning",
            "Deep Learning",
            "Natural Language Processing (NLP)",
            "Robotics & Automation",
            "Blockchain Technology",
            "Quantum Computing",
            "Augmented Reality (AR)",
            "Virtual Reality (VR)",
            "Internet of Things (IoT)",
            "Edge Computing",
            "5G Technology",
            "Cloud Computing",
            "Cybersecurity & Privacy",
            "Smart Cities",
            "Autonomous Vehicles",
            "Wearable Technologies",
            "Bioengineering & Biotechnology",
            "Genomics & CRISPR Technology",
            "Neurotechnology & Brain-Computer Interfaces",
            "Drones & UAVs",
            "3D Printing & Additive Manufacturing",
            "Blockchain & Cryptocurrencies",
            "Digital Twins",
            "Energy Storage & Green Tech",
            "Sustainable Technologies",
            "Smart Grids",
            "Quantum Cryptography",
            "Nanotechnology",
            "Advanced Materials Science",
            "Biometrics & Facial Recognition",
            "Voice Assistants & AI Chatbots",
            "HealthTech",
            "FinTech",
            "EdTech (Educational Technologies)",
            "AgricultureTech",
            "Space Technology",
            "Smart Home Technologies",
            "Gaming & eSports Innovations",
            "AI-powered Analytics",
            "Digital Transformation",
            "Human Augmentation",
            "Cloud-based AI Services",
            "Artificial General Intelligence (AGI)",
            "Autonomous Systems",
            "Cyber-Physical Systems",
            "Internet of Medical Things (IoMT)",
            "Swarm Robotics",
            "AI-powered Cybersecurity",
            "Blockchain in Supply Chain Management",
            "Synthetic Biology",
            "Quantum Machine Learning",
            "Smart Health Devices",
            "Voice-enabled IoT",
            "Robotic Process Automation (RPA)",

        // 🔹 Miscellaneous (5)
        "Astrology", "Paranormal Studies", "Self-Help & Motivation",
        "Ethics & Philosophy", "Cultural Studies"
      ],
      default: null // Subdomain is optional
    },

    bot_password: { type: String, required: true, minlength: 8 }, // Encrypted password
  },
  { timestamps: true }
);
chatbotSchema.pre("save", async function (next) {
  if (!this.isModified("bot_password")) return next();
  
  const salt = await bcrypt.genSalt(10);
  this.bot_password = await bcrypt.hash(this.bot_password, salt);
  next();
});
module.exports = mongoose.model("Chatbot", chatbotSchema);